services:
  traefik:
    image: traefik:v2.10
    command:
      - --configFile=/traefik.yml
    ports:
      - "80:80"
    networks:
      - his
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic.yml:/dynamic.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: auth.his-test.local
      KC_DB: dev-mem
    ports:
      - "8181:8080"
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak_import/test-realm.json:/opt/keycloak/data/import/test-realm.json:ro
    networks:
      - his

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.12.0
    extra_hosts:
      - "auth.his-test.local:host-gateway"
    volumes:
      - ./oauth2-proxy.cfg:/oauth2-proxy.cfg
    restart: on-failure
    ports:
      - "4180:4180"
    depends_on:
      - keycloak
    networks:
      - his
    command:
      - --config=/oauth2-proxy.cfg
networks:
  his:
    driver: bridge

