[package]
name = "app1"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = "1.0.228"
jsonwebtoken = "=9.3.1"
reqwest = { version = "0.12.23", features = ["json"] }
thiserror = "2"
